### ISSUE TITLE
Symfony 4 support & 3.0 release

### ISSUE THREAD

**Issue by pamil** [Lakion/ApiTestCase#112]
It would be great to support Symfony 4, what is needed for this to happen?

**Comment by emodric** [comment]
Isn't it already supported? https://github.com/Lakion/ApiTestCase/releases/tag/v3.0.0-RC.1 :)

**Comment by pamil** [comment]
What I meant was a stable release with Symfony 4 support, as I can't require release candidates in Sylius.

**Comment by emodric** [comment]
Ah, okay :)

Yes, 3.0 stable release would be welcome for me too :)

**Comment by lchrusciel** [comment]
I will do it at the end of February /  beginning of March

**Comment by emodric** [comment]
@lchrusciel Any news on 3.0 final release? :)

**Comment by lchrusciel** [comment]
The only thing that holds me back is unicode support. It will destroy builds of many people. I was thinking about some regression support with a new option, so you can turn on or off and remove it in ATC 4. It requires only one more condition here https://github.com/Lakion/ApiTestCase/blob/master/src/JsonApiTestCase.php#L90.

**Comment by emodric** [comment]
@lchrusciel Do you want something like this?

```
$jsonFlags = JSON_PRETTY_PRINT;
if (!isset($_SERVER['ESCAPE_JSON_UNICODE']) || true !== $_SERVER['ESCAPE_JSON_UNICODE']) {
    $jsonFlags = $jsonFlags | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES;
}

return json_encode(json_decode($content), $jsonFlags);

**Comment by lchrusciel** [comment]
Something like this. I will increase adoption of a newest version

**Comment by emodric** [comment]
Want me to do a PR with this or you had some more things in mind?

**Comment by lchrusciel** [comment]
If you only can I will really appreciate it

**Comment by emodric** [comment]
@lchrusciel https://github.com/Lakion/ApiTestCase/pull/113 :)

**Comment by lchrusciel** [comment]
ATC 3.0 has been just published! 🎉
