### ISSUE TITLE
Composer install throws an error with coduo/php-matcher

### ISSUE THREAD

**Issue by Schunk** [Lakion/ApiTestCase#41]
Hi, when doing composer require --dev lakion/api-test-case:dev-master@dev (since there is no stable version), i got the following errors:

```
  Problem 1
    - Installation request for lakion/api-test-case dev-master@dev -> satisfiable by lakion/api-test-case[dev-master].
    - lakion/api-test-case dev-master requires coduo/php-matcher ^2.1@dev -> no matching package found.
```

Could you please tell me what is wrong?

Thanks.

**Comment by bendavies** [comment]
It's because your composer min stability is too high.
do this:
`composer require lakion/api-test-case ^1.0@dev" coduo/php-matcher "^2.1@dev" --dev`

**Comment by lchrusciel** [comment]
We should update README probably...

**Comment by Schunk** [comment]
Thank you, I need to update my project dependencies to make it work, but a least now I understand!
