### ISSUE TITLE
[Bug] Cannot reference instances defined in another fixture yml file

### ISSUE THREAD

**Issue by steffenbrem** [Lakion/ApiTestCase#45]
When you have some base fixtures in `base_setup.yml` and you want to reference to one of the instances in there from another fixture file, lets say `products.yml`, you get:

```
UnexpectedValueException: Instance workspace_1 is not defined
```

I think this is caused by that the `loadFixturesFromFile` instantiates a new Alice `Loader` every time you load a fixture file (see: https://github.com/Lakion/ApiTestCase/blob/master/src/ApiTestCase.php#L279).

@pjedrzejewski Would it be a good solution if you instantiate the Alice Loader in the setup method, so that the fixture references are preserved when you load multiple fixture files in a single test?

**Comment by steffenbrem** [comment]
I have submitted a PR (#46) for this issue.

**Comment by michalmarcinkowski** [comment]
Thanks for fixing this!
