### ISSUE TITLE
No stable release?

### ISSUE THREAD

**Issue by printminion** [Lakion/ApiTestCase#59]
$ composer require --dev lakion/api-test-case

  [InvalidArgumentException]                                                                                                                            
  Could not find package lakion/api-test-case at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by lchrusciel** [comment]
We have not released a stable version yet. But we are planing to. Firstly we had to fix #57. For now it is only available in dev, so 
```bash
$ composer require --dev lakion/api-test-case "^1.0@dev"
```
should do the work.

**Comment by lchrusciel** [comment]
[Finally resolved!](https://github.com/Lakion/ApiTestCase/tree/v1.0.0)
