### ISSUE TITLE
ApiTestCase 1.0.0 Release cycle

### ISSUE THREAD

**Issue by lchrusciel** [Lakion/ApiTestCase#64]
It is about time to finally publish a stable release of this library. Because I'm really into merging some of awaiting PR's I have decide to publish an alpha version, to encourage us to finish them. I would like to publish a new version every week, until we reach a stable phase. 
 - [x] 1.0.0-alpha.1 - 19.07.2016
 - [x] 1.0.0-alpha.2 - 26.07.2016
 - [x] 1.0.0-rc - 2.08.2016
 - [x] 1.0.0 - 9.08.2016 🎉 

Between alpha1 and alpha2 I would like to merge #63, extract warning from #43 and maybe also add #52. Changes proposed in #60 could be added without BC Brakes so we can add them later.

Of course if there would be any further problems in a mean time, new versions could be added to this release cycle.

**Comment by lchrusciel** [comment]
[Fanfare](https://www.youtube.com/watch?v=Nmsn3t_4nNs), first stable release was published!

**Comment by pamil** [comment]
That should be [the fanfare](https://www.youtube.com/watch?v=dQw4w9WgXcQ).
