### ISSUE TITLE
PHPUnit 6 support in 2.0

### ISSUE THREAD

**Issue by emodric** [Lakion/ApiTestCase#86]
It would be awesome if 2.0 version of this lib supported PHPUnit 6, so we can use v1.x with PHPUnit 4.x and 5.x on PHP 5.6, and use version 2 with PHPUnit 6 on PHP 7.x

**Comment by lchrusciel** [comment]
@emodric nice idea! We will work on that!

**Comment by michalmarcinkowski** [comment]
If we will drop 5.6 support we will no longer be able to use it in Sylius 😢  not sure about that change... 😞

**Comment by emodric** [comment]
@michalmarcinkowski What do you mean? Sylius supports PHP 7.0.

**Comment by emodric** [comment]
The goal in my library would be to use `"lakion/api-test-case": "^1.0|^2.0"`, so the correct version based on version of PHP used would be installed.

**Comment by lchrusciel** [comment]
@emodric will it be possible? I heard some rumors, that it will be hard to support both PHPUnit 6 and the previous releases of this library because of namespace introduction.

**Comment by emodric** [comment]
It depends on what you use. PHPUnit 5.x has a forward compatibility layer for quite some time which enabled the use of `PHPUnit_Framework_TestCase` as `PHPUnit\Framework\TestCase`.

As of 5.7, there is a layer that enabled the use of `PHPUnit_Framework_Assert` as `PHPUnit\Framework\Assert`.

**Comment by nlegoff** [comment]
Hello, It would be awesome indeed tu support phpunit 6.x in 2.x version, we are currently stuck for upgrading to phpunit 6.x because of Lakion/ApiTestCase

**Comment by lchrusciel** [comment]
After a longer thinking it is not a case for a bumping major. Tag 1.2 will be enough.
