### ISSUE TITLE
Incompatibility with phpunit/dbunit

### ISSUE THREAD

**Issue by Snake-Tn** [Lakion/ApiTestCase#88]
It's not possible to use ApiTestCase with the official plugin [phpunit/dbunit](https://github.com/sebastianbergmann/dbunit)
Here is why:
**[ApiTestCase](https://github.com/Lakion/ApiTestCase/blob/master/src/ApiTestCase.php)** is overloading the **tearDown** method  and altering it's visibility from _protected_ to _public_. 
Doing so will prevent dbunit trait **[TestCaseTrait](https://github.com/sebastianbergmann/dbunit/blob/master/src/TestCaseTrait.php)** from overloading tearDown method. and a fatal exception is fired.

Here is an example of test who won't work :

```

namespace ApiBundle\Tests\Controller;

use Lakion\ApiTestCase\JsonApiTestCase;
use PHPUnit_Extensions_Database_TestCase_Trait;

class ProductControllerTest extends JsonApiTestCase
{
    use PHPUnit_Extensions_Database_TestCase_Trait;

}
```
> The best thing to do is avoiding any overloading.

**Comment by lchrusciel** [comment]
Would you like to contribute and solve this problem?
