### ISSUE TITLE
XmlApiTestCase cannot handle xml responses that include CDATA sections

### ISSUE THREAD

**Issue by Jan0707** [Lakion/ApiTestCase#98]
Hey everyone !

I am currently working on a REST api (using symfony + FOSRestBundle). My output is being serialised using JMSSerializer, which by default uses CDATA for escaping content. 
The CDATA section apparently cannot be parsed by the diffing mechanism you use.

Example:

```
1) ControllerTest::testList
"Array(1)" does not match "1".
@@ -1,15 +1,15 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <result>
-    <items>
-        <item>
-            <id>1</id>
-            <return_id>1</return_id>
-            <order_number>1</order_number>
-            <return_date>@string@.isDateTime()</return_date>
-            <created_at>@string@.isDateTime()</created_at>
-            <updated_at>@string@.isDateTime()</updated_at>
-        </item>
-    </items>
-    <count>1</count>
-    <total>1</total>
+  <items>
+    <item>
+      <id>1</id>
+      <return_id><![CDATA[1]]></return_id>
+      <order_number><![CDATA[1]]></order_number>
+      <return_date><![CDATA[2017-10-31T00:00:00+0100]]></return_date>
+      <created_at><![CDATA[2017-10-30T15:39:57+0100]]></created_at>
+      <updated_at><![CDATA[2017-10-30T15:39:57+0100]]></updated_at>
+    </item>
+  </items>
+  <count>1</count>
+  <total>1</total>
 </result>
```

Any idea on how to circumvent that ?

Kind regards,

Jan

**Comment by lchrusciel** [comment]
The diff is generated by php diff. In your example, the problem is with a number of spaces. You have defined 4 spaces and 2 are used in the returned value. We should improve this :)

**Comment by Jan0707** [comment]
While that might *also* be the case, the test passes, when I remove the cdata markup from the response, or include it in the expected response. Therefore, I do not think, that *only* the spaces are at fault.

**Comment by Jan0707** [comment]
Point in case, this is the diff, once I removed the extra white space:
```

"Array(1)" does not match "1".
@@ -3,11 +3,11 @@
   <items>
     <item>
       <id>1</id>
-      <return_id>1</return_id>
-      <order_number>1</order_number>
-      <return_date>@string@.isDateTime()</return_date>
-      <created_at>@string@.isDateTime()</created_at>
-      <updated_at>@string@.isDateTime()</updated_at>
+      <return_id><![CDATA[1]]></return_id>
+      <order_number><![CDATA[1]]></order_number>
+      <return_date><![CDATA[2017-10-31T00:00:00+0100]]></return_date>
+      <created_at><![CDATA[2017-11-01T08:19:59+0100]]></created_at>
+      <updated_at><![CDATA[2017-11-01T08:19:59+0100]]></updated_at>
     </item>
   </items>
   <count>1</count>
```

**Comment by lchrusciel** [comment]
One more time it is a case of diff. It just comparing two strings. I don't see any better solution rather than adding `![CDATA` to your code.

So either you need to define expected content as: `<return_date>![CDATA[@string@.isDateTime()]]</return_date>`
or configure JMS/change serializer in your app.

**Comment by Jan0707** [comment]
Oh, apparently there was a misunderstanding here. I see what you mean here now. I simply didn't realise that the @string@ markup would be parsed when used within the CDATA tag. 

I did what you suggested and it seems to work just fine. Sorry for the inconvenience and thanks a lot !
