### ISSUE TITLE
Support for nelmio/alice 3

### ISSUE THREAD

**Issue by viscat** [Lakion/ApiTestCase#99]
There's any plan of upgrading support of `nelmio/alice` to version 3? Has it been studied? 

Now I'm getting a lot of deprecation warnings as many of the features I'm using are being dropped in version 3. If you have not taken a look, I can see if it would be easy.

Thanks!

**Comment by lchrusciel** [comment]
We need somebody to take a look into that. Are you willing to help @viscat?

**Comment by viscat** [comment]
I will take a look into that then. I will update this issue or open a PR soon.

**Comment by lchrusciel** [comment]
Thank you :)

**Comment by lchrusciel** [comment]
Closed by #100
